org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true

minecraft_version=1.21.11
neoForm_version=1.21.11-20251209.172050
parchment_minecraft=1.21.11
parchment_version=2025.12.20
# NeoForge Properties
neo_loader_version=2
neoforge_version=21.11.28-beta
# Fabric Properties
fabric_loader_version=0.18.4

# Mod Properties
mod_name=Smart Keep Inventory
mod_id=smart_keep_inventory
mod_version=1.0.1
description=Allows enabling keep inventory only under certain conditions
mod_author=Flemmli97
license=MIT
maven_group=io.github.flemmli97
issue_tracker=https://github.com/Flemmli97/SmartKeepInventory/issues
sources_url=https://github.com/Flemmli97/SmartKeepInventory

# Dependencies
fabric_api_version=0.141.1+1.21.11

# Curse properties
curseforge_versions=1.21.11, Java 21
curseforge_page=https://www.curseforge.com/minecraft/mc-mods/smart-keep-inventory
curseforge_id=1424832
curseforge_dep_fabric=fabric-api
curseforge_dep_neoforge=
modrinth_versions=1.21.11
modrinth_page=https://modrinth.com/mod/smart-keep-inventory
modrinth_id=qeGAjqzW
modrinth_dep_fabric=fabric-api
modrinth_dep_neoforge=

# Other
project_name=SmartKeepInventory
full_changelog=https://github.com/Flemmli97/SmartKeepInventory/blob/1.21.11/Changelog.md