org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true

jvm=25
minecraft_version=26.2
neoForm_version=26.2-2
# NeoForge Properties
neoforge_version=26.2.0.63
# Fabric Properties
fabric_loader_version=0.19.3

# Mod Properties
mod_name=Smart Keep Inventory
mod_id=smart_keep_inventory
mod_version=1.1.0
description=Allows enabling keep inventory only under certain conditions
mod_author=Flemmli97
license=MIT
maven_group=io.github.flemmli97
issue_tracker=https://github.com/Flemmli97/SmartKeepInventory/issues
sources_url=https://github.com/Flemmli97/SmartKeepInventory

# Dependencies
fabric_api_version=0.158.0+26.2

# Curse properties
curseforge_versions=26.2, Java 25, server
curseforge_page=https://www.curseforge.com/minecraft/mc-mods/smart-keep-inventory
curseforge_id=1424832
curseforge_dep_fabric=fabric-api
curseforge_dep_neoforge=
modrinth_versions=26.2, server
modrinth_page=https://modrinth.com/mod/smart-keep-inventory
modrinth_id=qeGAjqzW
modrinth_dep_fabric=fabric-api
modrinth_dep_neoforge=

# Other
project_name=SmartKeepInventory
full_changelog=https://github.com/Flemmli97/SmartKeepInventory/blob/26.2/Changelog.md